name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      id: prepare
      run: |
        echo "::set-output name=name::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
        echo "::set-output name=prefix::$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER"
    - name: Build
      run: docker build . --file ./build/Dockerfile
        --tag $IMAGE_NAME:$IMAGE_VERSION
        --tag $IMAGE_NAME:latest
        --build-arg VERSION_PREFIX=$IMAGE_VERSION
        --build-arg VERSION_SUFFIX=test
      env:
        IMAGE_NAME: ${{ steps.prepare.outputs.name }}
        IMAGE_VERSION: ${{ steps.prepare.outputs.prefix }}
